services:
  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'

  mariadb:
    image: mariadb:11.2
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword123
      - MARIADB_USER=bn_opencart
      - MARIADB_PASSWORD=password123
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'

  opencart:
    image: agridyaev/opencart:4.0.2-3-debian-12-r33
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_PASSWORD=password123
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      opencart:
        condition: service_healthy
    environment:
      - BASE_URL=http://${LOCAL_IP}:${OPENCART_PORT}
    command: ["-v", "-s", "tests/", "--url", "http://${LOCAL_IP}:${OPENCART_PORT}"]

networks:
  default:
    external:
      name: selenoid
